python main.py \
    --json_list='/home/yusongli/Documents/research-contributions/UNETR/BTCV/dataset/meta_data2.yaml' \
    --gpu=0 \
    --max_epochs=100 \
    --roi_x=96 \
    --roi_y=96 \
    --roi_z=96 \
    --model_name='unetr' \
    --pos_embed='conv' \
    --trainset_cache_num=1332 \
    --valset_cache_num=332 \
    --testset_cache_num=264 \
    --a_min=0 \
    --a_max=1500 \
    --use_normal_dataset
