python main.py \
--json_list='/home/yusongli/Documents/shidaoai_new_project/data/meta_data2.yaml' \
--gpu=5 \
--max_epochs=100 \
--roi_x=96 \
--roi_y=96 \
--roi_z=96 \
--model_name='unetr' \
--trainset_cache_num=1332 \
--valset_cache_num=332 \
--testset_cache_num=264 \
